include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [lib/firebase_options.dart]

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    one_member_abstracts: false
