name: todo_list_provider
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.7
  synchronized: ^3.1.0
  path: ^1.8.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
